config/routes.rb
Rails.application.routes.draw do
  resources :event_videos
  resources :events
  resources :transactions,  only: [:new, :create]
  resources :user_accounts, only: [:update, :edit]
  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" } 
  root 'home#search_results'
  post '/add_to_cart' => "home#add_to_cart",as: :add_to_cart
  get '/add_to_cart' => "home#add_to_cart",as: :add_to_cart_after_sign_in
  get '/checkout' => "home#checkout",as: :checkout
  post '/pay' => "home#pay"
  get '/events/:event_id/videos' => "event_videos#show_event_videos",as: :show_event_videos
  get '/upload_video' => "event_videos#upload_video",as: :upload_video
  get '/purchases' => "home#purchases",as: :purchases
  get '/places' => "home#places",as: :places
  get '/search' => "home#search_results",as: :search
  get '/search_api' => "home#search_api",as: :search_api
  post '/save_video' => "event_videos#save_video",as: :save_video
  get '/event_videos/new/:event_id' => "event_videos#new",as: :event_video_event
  get '/save_static_camera' => "static_camera#new", as: :save_static_camera
  get '/delete_static_camera' => "static_camera#delete"
  post '/create_camera' => "static_camera#create", as: :create_camera
  post '/destroy_camera' => "static_camera#destroy"
  get '/report_spam' => "event_videos#report_spam"
  post '/update_spam' => "event_videos#update_spam"
  get '/subscribe/:event_id' => "events#subscribe", as: :subscribe_event
  get '/unsubscribe/:event_id' => "events#unsubscribe", as: :unsubscribe_event
  post '/remove_from_cart' => "home#remove_from_cart", as: :remove_from_cart
  post '/paypalNotification' =>"paypal#notification"
  get '/success' => "paypal#success"
  get '/execute' => "paypal#execute"
  get '/cancelled' => "paypal#cancelled"
  post '/setup_purchase' => "paypal#setup_purchase"

  get '/videos' => 'user_accounts#uploaded_videos'
  get '/user_events' => 'user_accounts#events'
  get '/cameras' => 'user_accounts#cameras'
  get '/payments' => 'user_accounts#payments'
  patch '/update_payment_info' => 'user_accounts#update_payment_info'

  get '/download' => "home#download_video"

end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
	before_action :check_user, only: [:edit, :update]
	before_action :sign_in_check
	before_action :set_user_account, only: [:edit, :update]
	before_action :set_user, only: [:uploaded_videos, :events, :cameras, :payments, :update_payment_info]
	
	def edit
		@countries  = { "United States (+1)" => "+1", "Switzerland (+41)" => "+41" }
	end

	def update
		if @user_account.update(user_account_params)
			redirect_to edit_user_account_path(@user_account), notice: 'Updated Successfully'
		else
			flash[:alert] = "Please Try Again."
			render 'edit'
		end
	end

	def uploaded_videos
		
		@videos = @user.event_videos
	end

	def events 
		@events = @user.events
		@subscribed_events = @user.subscribed_events
	end

	def cameras
		@cameras = @user.static_cameras
	end

	def payments
		@videos = @user.event_videos
	end

	def update_payment_info
		puts "user info"
		puts @user
		if @user.update(user_payment_info_params)
			redirect_to payments_path, notice: 'Updated Successfully'
		else
			flash[:alert] = "Please Try Again."
			render 'payments'
		end
	end

	private

	def check_user
		user_id = current_user.id
		check_user = UserAccount.where(user_id: user_id)
		if check_user.empty?
			UserAccount.create("user_id" => user_id)
		end
	end

	def sign_in_check
	    if not user_signed_in?
	      redirect_to new_user_session_path
	    end
    end

    def set_user
    	user_id = current_user.id
    	@user = User.find(user_id)
    end
    
    def set_user_account
    	user_id = current_user.id
    	@user_account = UserAccount.where("user_id" => user_id).first
    end

    def user_account_params
    	params.require(:user_account).permit(:first_name, :last_name, :address_line_1, :address_line_2, :city, :country, :zipcode, :country_code, :phone)
    end

    def user_payment_info_params
    	params.require(:user).permit(:paypal_email, :paypal_paykey)
    end
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/views/user_accounts/_sidebar.html.erb
<div class="container">
<div class="row">
	<div class="col-md-2">
		<div class="nav nav-pills nav-stacked">
			  <li role="presentation" class="<%= 'active' if params[:action] == 'edit' %>"><%= link_to "Edit Account", edit_user_account_path(current_user) %></li>
			  <li role="presentation" class="<%= 'active' if params[:action] == 'uploaded_videos' %>"><%= link_to "Videos", videos_path %></li>
			  <li role="presentation" class="<%= 'active' if params[:action] == 'events' %>"><%= link_to "Events", user_events_path %></li>
			  <li role="presentation" class="<%= 'active' if params[:action] == 'cameras' %>"><%= link_to "Cameras", cameras_path %></li>
			  <li role="presentation" class="<%= 'active' if params[:action] == 'payments' %>"><%= link_to "Payments", payments_path %></li>
		</div>

	</div>


	<div class="col-md-10">

app/views/user_accounts/cameras.html.erb
<%= render :partial => 'sidebar' %>
<h1>Cameras</h1>
<% @cameras.each do |camera| %>
	<%= camera.location_name %> <br>
	<%= link_to "View on map", root_path(:lat => camera.latitude, :lng=> camera.longitude) %>
<% end %>


</div>

</div>

app/views/user_accounts/edit.html.erb
<br>
<%= render :partial => 'sidebar' %>
<div class="container-fluid">


<%= flash[:notice] %>
<%= flash[:alert] %>

<div class="row">

<div class="col-md-6">
<%= form_for @user_account, :html => { :class => "form-horizontal" } do |f| %>

  <% if @user_account.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user_account.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @user_account.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
  </div> 
  <div class="form-group">
    <%= f.label :last_name, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address_line_1, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
      <%= f.text_area :address_line_1, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address_line_2, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
      <%= f.text_area :address_line_2, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :city, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :country, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
      <%= f.country_select :country, {}, {:class => 'form-control'} %>
      
    </div>
  </div>

   

  <div class="form-group">
    <%= f.label :zipcode, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :zipcode, :class => 'form-control' %>
    </div>
  </div>

  


  <div class="form-group">
    <%= f.label :country_code, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
	  <%= f.select_tag :country_code, 
	                  options_for_select(@countries, :selected => f.object.country_code), name: "user_account[country_code]", :class => 'form-control' 
	  %>
  	</div>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'col-md-4 control-label' %>
    <div class="col-md-8">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
  </div>
  

  
    
  <div class="form-group">
    <div class="col-md-offset-4">
      <%= f.submit nil, :class => 'btn btn-primary' %>
     
    </div>
  </div>
<% end %>

</div>

</div>

</div>

</div>

</div>

</div>

app/views/user_accounts/events.html.erb
<br>
<%= render :partial => 'sidebar' %>

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-justified" role="tablist">
    <li role="presentation" class="active"><a href="#create" aria-controls="create" role="tab" data-toggle="tab">Created Event</a></li>
    <li role="presentation"><a href="#subscribe" aria-controls="subscribe" role="tab" data-toggle="tab">Subscribed Event</a></li>
    
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="create">
    	
    	<h1 class="title-style-1">Created Events</h1>

<% @events.each do |event| %>

	<h1 class="title-style-2"> <span class="fa fa-map-marker"></span> <%= event.location_name %> </h1>
	
			<% if event.event_videos.empty? %>
				<br>
				<p class="text-center">No Videos Found</p>
				<br>
			<% else %>
			
				<div class="row">

				<% event.event_videos.each do |video| %>
					
					<div class="col-md-4">
						<div class="panel panel-default">
						    <div class="panel-body">
						   
						       
						          <div class="panel panel-default my_panel">
						            <div class="panel-body">
						            	<%= image_tag(video.video.thumb.pic_1.url, :class => 'img-responsive center-block') %>
						             
						            </div>
						            <div class="panel-footer">
						              <h3>The company</h3>
						              <p><%= video.event.location_name %></p>
						              <a href="#" class="btn btn-primary">Read More</a>
						            </div>
						          </div>
						     
						    </div>
						  </div>
					</div>
					
					
				<% end %>
			
				</div>
			
			<% end %>
	

	
<% end %>



    </div>
    <div role="tabpanel" class="tab-pane" id="subscribe">
    	
    	<h1 class="title-style-1">Subscribed Events</h1>

<% @subscribed_events.each do |event| %>
	<h1 class="title-style-2"> <span class="fa fa-map-marker"></span> <%= event.location_name %> </h1>
	
			<% if event.event_videos.empty? %>
				<br>
				<p class="text-center">No Videos Found</p>
				<br>
			<% else %>
			
				<div class="row">

				<% event.event_videos.each do |video| %>
					
					<div class="col-md-4">
						<div class="panel panel-default">
						    <div class="panel-body">
						   
						       
						          <div class="panel panel-default my_panel">
						            <div class="panel-body">
						            	<%= image_tag(video.video.thumb.pic_1.url, :class => 'img-responsive center-block') %>
						             
						            </div>
						            <div class="panel-footer">
						              <h3>The company</h3>
						              <p>L<%= video.event.location_name %></p>
						              <a href="#" class="btn btn-primary">Read More</a>
						            </div>
						          </div>
						     
						    </div>
						  </div>
					</div>
					
					
				<% end %>
			
				</div>
			
			<% end %>
<% end %>

    </div>
    
  </div>

</div>






</div>

</div>

app/views/user_accounts/payments.html.erb
<br>
<%= render :partial => 'sidebar' %>

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-justified" role="tablist">
    <li role="presentation" class="active"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
    
    <li role="presentation"><a href="#payment_status" aria-controls="payment_status" role="tab" data-toggle="tab">Transactions</a></li>
    
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="settings">
        
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
        <br>
        <br>
        <%= form_for @user, :url => { :action => "update_payment_info", :id => @user, :controller => "user_accounts" }, :html => { :class => "form-horizontal" } do |f| %>

          <% if @user.errors.any? %>
            <div id="error_expl" class="panel panel-danger">
              <div class="panel-heading">
                <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this event from being saved:</h3>
              </div>
              <div class="panel-body">
                <ul>
                  <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :paypal_email, :class => 'control-label col-md-4' %>
            <div class="col-md-8">
              <%= f.text_field :paypal_email, :class => 'form-control' %>
            </div>
          </div> 
             
          <div class="form-group">
            <div class="col-md-offset-4">
              <%= f.submit nil, :class => 'btn btn-primary' %>
             
            </div>
          </div>
        <% end %>

        </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="payment_status">

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Thumbnail</th>
          <th>Location</th>
          <th>Status</th>
           <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        
     

        <% @videos.each do |video| %>
  
           <% if !video.purchases.empty? %>
         
          
            <% video.purchases.each do |payment| %>
                <% if payment.payment_status == 'COMPLETED' %>
                    <tr class="success">
                <% else %>
                    <tr class="warning">
                <% end %>
               
                 <td><%= image_tag(video.video.thumb.pic_1.url, :class => 'img-small') %></td>
                 <td> <%= video.event.location_name %></td>
              
                 <td><%= payment.payment_status %></td>
                 <td><%= payment.amount %></td>
               </tr>
            <% end %>
          
          

          <% end %>
          
         

                  
      <% end %>
        </tbody>
        </table>

    </div>
    
  </div>

</div>








</div>

</div>

app/views/user_accounts/uploaded_videos.html.erb
<br>
<%= render :partial => 'sidebar' %>



<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>Thumbnail</th>
			<th>Location</th>
			<th>Total Downloads</th>
		</tr>
	</thead>
	<tbody>
		<% @videos.each do |video| %>
			<tr>
				<td><%= image_tag(video.video.thumb.pic_1.url, :class => 'img-small') %></td>
				<td><%= video.event.location_name %></td>
				<td><%= video.purchases.count %></td>
			</tr>
		<% end %>
	</tbody>
</table>



</div>

</div>

</div>

</div>