config/routes.rb
Rails.application.routes.draw do
  resources :event_videos
  resources :events
  resources :transactions,  only: [:new, :create]
  resources :user_accounts, only: [:update, :edit]
  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" } 
  root 'home#search_results'
  post '/add_to_cart' => "home#add_to_cart",as: :add_to_cart
  get '/add_to_cart' => "home#add_to_cart",as: :add_to_cart_after_sign_in
  get '/checkout' => "home#checkout",as: :checkout
  post '/pay' => "home#pay"
  get '/events/:event_id/videos' => "event_videos#show_event_videos",as: :show_event_videos
  get '/upload_video' => "event_videos#upload_video",as: :upload_video
  get '/purchases' => "home#purchases",as: :purchases
  get '/places' => "home#places",as: :places
  get '/search' => "home#search_results",as: :search
  get '/search_api' => "home#search_api",as: :search_api
  post '/save_video' => "event_videos#save_video",as: :save_video
  get '/event_videos/new/:event_id' => "event_videos#new",as: :event_video_event
  get '/save_static_camera' => "static_camera#new", as: :save_static_camera
  get '/delete_static_camera' => "static_camera#delete"
  post '/create_camera' => "static_camera#create", as: :create_camera
  post '/destroy_camera' => "static_camera#destroy"
  get '/report_spam' => "event_videos#report_spam"
  post '/update_spam' => "event_videos#update_spam"
  get '/subscribe/:event_id' => "events#subscribe", as: :subscribe_event
  get '/unsubscribe/:event_id' => "events#unsubscribe", as: :unsubscribe_event
  post '/remove_from_cart' => "home#remove_from_cart", as: :remove_from_cart
  post '/paypalNotification' =>"paypal#notification"
  get '/success' => "paypal#success"
  get '/execute' => "paypal#execute"
  get '/cancelled' => "paypal#cancelled"
  post '/setup_purchase' => "paypal#setup_purchase"

  get '/videos' => 'user_accounts#uploaded_videos'
  get '/user_events' => 'user_accounts#events'
  get '/cameras' => 'user_accounts#cameras'
  get '/payments' => 'user_accounts#payments'
  patch '/update_payment_info' => 'user_accounts#update_payment_info'

  get '/download' => "home#download_video"

end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_taggable_on :categories
  acts_as_mappable :default_units => :miles,:default_formula => :sphere, :lat_column_name => :latitude, :lng_column_name => :longitude
  has_many :event_videos
  belongs_to :user
  has_many :subscriptions
  has_many :subscribed_users, through: :subscriptions, source: :user
  validates_presence_of :latitude
  validates_presence_of :longitude
  validates_presence_of :date_of_occurence

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :sign_in_check, only: [:create,:update,:destroy]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all.includes(:categories)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @response = Hash.new
    if user_signed_in?
      @event = Event.new
      if not session[:redirect_to].nil? 
        redirect_url = session[:redirect_to]
        session[:redirect_to] = nil
        redirect_to redirect_url
      end
    else
      #session[:redirect_to] = request.referrer
      @response["status"] = 1
      @response["message"] = "Please sign in before creating video"
    end
  end

  # GET /events/1/edit
  def edit
    if not @event.user_id == current_user.id
      flash[:danger]  = "You are not authorized"
      redirect_to root_path
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.category_list = params[:event][:category_list]

    
    #Notify static camera users, if event is created near to user's static camera
    pos = [@event.latitude, @event.longitude]
    static_camera_users = StaticCamera.select(:user_id).within(50, :origin => pos).uniq
    user = Array.new
    
    static_camera_users.each do |u|
      user.push(u.user_id)
    end

    if @event.save
      UserMailer.static_camera_notify(user, @event).deliver_later
      flash[:success] = 'Event was successfully created.' 
      marker_array = [@event.id,@event.location_name,@event.latitude,@event.longitude]
      gon.markers_location = marker_array
      redirect_to root_path
    else
      flash[:success] = 'Error Creating Event' 
      redirect_to root_path
    end
  end

 
   # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        flash[:success] = 'Event was successfully updated.' 
        format.html { redirect_to @event}
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    if not @event.user_id == current_user.id
      flash[:danger]  = "You are not authorized"
      redirect_to root_path
    else
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url, success: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

  end

  def subscribe
    @event_id = params[:event_id]
    @user_id = current_user.id
    Subscription.create(user_id: @user_id, event_id: @event_id)
    respond_to do |format|
      format.js   { render :layout => false }
    end
  end 

  def unsubscribe
    @event_id = params[:event_id]
    @user_id = current_user.id
    subs = Subscription.where(user_id: @user_id, event_id: @event_id).first
    subs.destroy
    respond_to do |format|
      format.js   { render :layout => false }
    end
  end 

  private
  def sign_in_check
    if not user_signed_in?
      redirect_to new_user_session_path
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:latitude, :longitude, :date_of_occurence, :time_of_occurence, :location_name,:place_id,:category_list,:description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, :html => { :class => "form-horizontal event" } do |f| %>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
    <div class="form-group">
    <%= f.label :location_name, :class => 'control-label col-lg-4' %>
    <div class="col-lg-8">
      <%= f.text_area :location_name, :class => 'form-control' %>
    </div>
  </div>

  
      <%= f.hidden_field :latitude, :class => 'form-control' %>
   
  
      <%= f.hidden_field :longitude, :class => 'form-control' %>
    

   <div class="form-group">
    <%= f.label :date_of_occurence, :class => 'control-label col-lg-4' %>
    <div class="col-lg-8">
      <%= f.text_field :date_of_occurence, :class => 'form-control' %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :time_of_occurence, :class => 'control-label col-lg-4' %>
    <div class="col-lg-8">
      <%= f.text_field :time_of_occurence, :placeholder => 'eg: (13.30) hrs' ,:class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-4' %>
    <div class="col-lg-8">
      <%= f.text_area :description, :class => 'form-control' %>
      <p class="error-flag">No special characters or phone numbers are allowed!</p>
    </div>
  </div>
 <div class="form-group">
    <%= f.label :tags, :class => 'control-label col-lg-4' %>

    <div class="col-lg-8">
      <div class="checkbox">
        <label> <%= f.check_box :category_list, { :multiple => true }, 'accident', nil  %> Accident </label>
        <label> <%= f.check_box :category_list, { :multiple => true }, 'theft', nil  %> Theft / Burglary </label>
        <label> <%= f.check_box :category_list, { :multiple => true }, 'assault', nil  %> Assault </label>
        <label> <%= f.check_box :category_list, { :multiple => true }, 'vandalism', nil   %> Vandalism </label>
        <label> <%= f.check_box :category_list, { :multiple => true }, 'disaster', nil   %> Disaster </label>
        <label> <%= f.check_box :category_list, { :multiple => true }, 'driving', nil   %> Reckless/Dangerous Driving </label>
        <label> <%= f.check_box :category_list, { :multiple => true }, 'roadrage', nil   %> Road Rage </label>
        <label> <%= f.check_box :category_list, { :multiple => true }, 'other', nil   %> Other </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.text_field :place_id, :class => 'form-control hidden' %>
  </div>
  <div class="alert alert-warning alert-message-popup" role="alert">
    <input type="checkbox" id="accept" class="accept" onchange="document.getElementById('create_event').disabled = !this.checked;">
    <span>Events cannot be edited or deleted once created</span>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-4 col-lg-8">
      <%= f.submit nil, :class => 'btn btn-primary', :id => 'create_event' %>
      <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
    </div>
  </div>
<% end %>

app/views/events/_form_video.html.erb
<%= form_for @event, :html => { :class => "form-horizontal event" ,:multipart => true},:url =>"save_video",:multipart => "true" do |f| %>

  <% if @event.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :latitude, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :latitude, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :longitude, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_of_occurence, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :date_of_occurence, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tags, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%=text_field("event","category_list") %>
    </div>
  </div>

  <div class="form-group">
    <%= f.text_field :place_id, :class => 'hidden' %>
  </div>

  <div class="form-group">
    <label class="control-label col-lg-2">Select your video</label>
    <input type="file" class="form-control" name="event[video]"/>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),events_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%- model_class = Event -%>
<%if current_user.stripe_access_token.nil?%>
  <a href="/users/auth/stripe_connect"> Link Stripe </a>
<%end%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:date_of_occurence) %></th>
      <th><%= model_class.human_attribute_name(:location_name) %></th>
      <th>Tags</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.id, event_path(event) %></td>
        <td><%= event.latitude %></td>
        <td><%= event.longitude %></td>
        <td><%= event.date_of_occurence %></td>
        <td><%= event.location_name %></td>
        <td>
          <%event.categories.each do |category| %>
            <%=category.name%>
          <%end%>
        </td>
        <td>
          <%= link_to "Show videos linked to this event",show_event_videos_path(event.id),:class=>"btn btn-default btn-xs",:remote => true%>
          <%= link_to t('.show', :default => t("helpers.links.show")),event_path(event), :class => 'btn btn-default btn-xs' %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Event',new_event_path,:class => 'btn btn-primary',:remote=> true %>
<div id="new_event_form"></div>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/new.js.erb
<%if @response["status"] == 1%>
  $("#login").modal("show");
<%else%>
$('#new_event_form').html("<%= j (render 'form') %>");

var lat = $("#hidden_lat").val();
var lng = $("#hidden_lng").val();
var place_id = $("#hidden_place_id").val();
var place_address = $("#hidden_address").val();
$("#event_latitude").val(lat);
$("#event_longitude").val(lng);
$("#event_location_name").val(place_address);
$("#place_id").val(place_id);
$("#event_latitude").attr('readonly',true);
$("#event_longitude").attr('readonly',true);
$("#event_location_name").attr('readonly',true);
$('#create_event').prop('disabled', true);
$("#event_date_of_occurence").datetimepicker({
  maxDate: 0,
  step: 30,
  timepicker:false,
  format:'d M Y',
  defaultDate:new Date()
});


$("#event_description").keyup(function(){ validateDescription($(this).val())});


$("#event_date_of_occurence").val(formatDate(new Date()));
$("#event_time_of_occurence").datetimepicker({
  	datepicker: false,
    format:'H:i'
});

function validateDescription(text)
{

  var pattern = /[0-9]{5}|[@#$%&*()_+.[\]{}?]*$/
  if(text.match(pattern)[0]!= "") {
     
      value = $("#event_description").val();
      value = value.replace(pattern, "");
      $("#event_description").val(value);
      $('.error-flag').fadeIn(1000);
     
  }
  else{
     $('.error-flag').fadeOut(2500);
  }

}

function formatDate(date) {
  var monthNames = [
    "Jan", "Feb", "Mar",
    "Apr", "May", "Jun", "Jul",
    "Aug", "Sep", "Oct",
    "Nov", "Dec"
  ];

  var day = date.getDate();
  var monthIndex = date.getMonth();
  var year = date.getFullYear();

  return day + ' ' + monthNames[monthIndex] + ' ' + year;
}
$('#cv_create_title').text("Creat Event (Request Video)");
$("#cv_create").modal("show");
<%end%>

app/views/events/show.html.erb
<br/>
<br/>
<br/>
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @event.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @event.longitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_of_occurence) %>:</strong></dt>
  <dd><%= @event.date_of_occurence %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location_name) %>:</strong></dt>
  <dd><%= @event.location_name %></dd>
  <% @event.category_list.each do |category|%> 
    <dd> <%=category%>
  </dd>
<%end%>
</dl>
<%= link_to "Return to search",root_path, :class => 'btn btn-default'  %>

app/views/events/subscribe.js.erb
var new_href = $('#notify-btn').attr('href');
new_href = new_href.replace("subs", "unsubs");


$('#notify-btn').removeClass('btn-primary btn-default').addClass('btn-danger').attr('href', new_href).html('Don\'t Notify Me');

app/views/events/unsubscribe.js.erb
var new_href = $('#notify-btn').attr('href');
new_href = new_href.replace("un", "");

$('#notify-btn').removeClass('btn-default btn-danger').addClass('btn-primary').attr('href', new_href).html('Notify Me');